name: Homebridge
version: 0.2.0-1
stage: experimental
slug: homebridge
description: Lightweight HomeKit API implementation with plugin support
url: https://github.com/dvdblg/hassio-addons/tree/main/homebridge
arch:
  - armv7
  - aarch64
  - amd64
ports:
  8581/tcp: 8581
ports_description:
  8581/tcp: Homebridge UI
ingress: true
ingress_port: 8581
panel_icon: mdi:home-automation
host_network: true
init: false
map:
  - addon_config:rw
image: ghcr.io/dvdblg/{arch}-addon-homebridge
